#!/usr/bin/env bash
set -e

get_python_binary() {
  BASE_PATH="/usr/bin/python"
  PYTHON_DISTROS="$(ls ${BASE_PATH}* | tr '\n' ' ')"

  if [ "${PYTHON_DISTROS}" != "" ]; then
    BASE_PATH_LEN=${#BASE_PATH}
    VERSION_REQEX='^[0-9]+([.][0-9]+)?$'

    NEWEST_VERSION=""
    for DISTRO in ${PYTHON_DISTROS:1}; do
        DISTRO_VERSION="${DISTRO:$BASE_PATH_LEN}"
        if [[ "${DISTRO_VERSION}" =~ ${VERSION_REQEX} ]] && [[ "${DISTRO_VERSION}" > "${NEWEST_VERSION}" ]];
        then
          NEWEST_VERSION="${DISTRO_VERSION}"
        fi
    done

    if [ "${NEWEST_VERSION}" != "" ]; then
        echo "${BASE_PATH}${NEWEST_VERSION}"
    else
        echo "${BASE_PATH}"
    fi
  fi
}

PYTHON_BIN="$(get_python_binary)"
if [ "${PYTHON_BIN}" == "" ]; then
  echo "Python distribution not found"
  exit 1
fi

echo "Running jtop with ${PYTHON_BIN}..."
"${PYTHON_BIN}" ./jtop.py $@
